title: INDEX
email: your-email@example.com
author: "Nuno Moura"
linkedin: "https://www.linkedin.com/in/nunobmoura/"

description: >-
  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur libero iste enim perferendis quaerat iure. Velit laudantium architecto vel sapiente perspiciatis.
baseurl: "/project_index" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  profiles:
    output: true