title: INDEX
email: your-email@example.com
author: "Nuno Moura"
linkedin: "https://www.linkedin.com/in/nunobmoura/"
fabricio_linkedin: "https://www.linkedin.com/in/fabricioteixeira/"


description: >-
  IndeX is not like any other platform on the internet. The only purpose is to help you find compelling ideas, knowledge, and perspectives. IndeX is home to thousands of independent voices.
baseurl: "/project_index" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  profiles:
    output: true
    permalink: /:title
  
  categories:
    output: true
    permalink: /:title

permalink: /:slug